INSERT INTO follows(user_id, follows_id, followers_id) VALUES('1', '2', '5');
INSERT INTO follows(user_id, follows_id, followers_id) VALUES('1', '4', '2');
INSERT INTO follows(user_id, followers_id) VALUES('1', '6');
INSERT INTO follows(user_id, followers_id) VALUES('1', '3');
INSERT INTO follows(user_id, follows_id, followers_id) VALUES('2', '7', '1');
INSERT INTO follows(user_id, follows_id, followers_id) VALUES('2', '1', '3');
INSERT INTO follows(user_id, follows_id, followers_id) VALUES('3', '1', '4');
INSERT INTO follows(user_id, follows_id) VALUES('3', '2');
INSERT INTO follows(user_id, follows_id) VALUES('3', '7');
INSERT INTO follows(user_id, follows_id, followers_id) VALUES('4', '3', '1');
INSERT INTO follows(user_id, follows_id) VALUES('4', '7');
INSERT INTO follows(user_id, follows_id, followers_id) VALUES('5', '2', '7');
INSERT INTO follows(user_id, followers_id) VALUES('5', '6');
INSERT INTO follows(user_id, follows_id, followers_id) VALUES('6', '5', '7');
INSERT INTO follows(user_id, follows_id) VALUES('6', '1');
INSERT INTO follows(user_id, follows_id, followers_id) VALUES('7', '6', '2');
INSERT INTO follows(user_id, follows_id, followers_id) VALUES('7', '5', '3');
INSERT INTO follows(user_id, followers_id) VALUES('7', '4');